### ISSUE TITLE
Layer-wise T-S Learning attention dimensions is mismatch.

### ISSUE THREAD

**Issue by TeaPoly** [Sanyuan-Chen/CSS_with_TSTransformer#1]
Thanks to the author for providing a method for denoising distillation learning, it's very helpful for me. 
But I noticed that  attention dimensions is mismatch in Layer-wise T-S Learning. The layer-wise is MSE loss.

<img width="932" alt="截屏2022-05-16 11 45 32" src="https://user-images.githubusercontent.com/3815778/168516499-968251aa-81d2-4c94-8bbe-19631ad23569.png">

But teacher and student hidden dimension is different. I don't quite understand how the loss function is calculated at this time, please guide me.

<img width="883" alt="截屏2022-05-16 11 22 55" src="https://user-images.githubusercontent.com/3815778/168516505-5bbf972c-e702-4874-b14a-e09813c98e0d.png">

**Comment by Sanyuan-Chen** [comment]
Hi @TeaPoly ,

Thanks for your interest! In our implementation, we simply use a linear layer with no bias to project the hidden states of the teacher model to the same dimension as the student model.

**Comment by TeaPoly** [comment]
> project

Thanks for you reply.

**Comment by TeaPoly** [comment]
> linear layer with no bias to project the hidden states of the teacher model

I found that the loss of MSE drops faster. I feel like projection is easy to learn.  I have two question to ask:

1. Is it a linear layer shared in different layer-wise hidden, or there different linear layer in different layer-wise hidden.
2. Are there weight of (multiple/one) linear is always trainable?

**Comment by Sanyuan-Chen** [comment]
Hi, the linear projection is not shared for different layers, and the weights are trainable during training.

**Comment by TeaPoly** [comment]
> Hi, the linear projection is not shared for different layers, and the weights are trainable during training.

Thanks for your reply.
